### ISSUE TITLE
Add 'css' strategy with postcss

### ISSUE THREAD

**Issue by ivanvotti** [ivanvotti/ember-svg-jar#8]
Example:

```css
/* before */
.pattern {
  background: svg-jar("asset-name", fill=#000);
}

/* after */
.pattern {
  background: url("data:image/svg+xml;charset=utf-8,%3Csvg fill='#000' viewBox='0 0 24 24' xmlns='http://www.w3.org/2000/svg'%3E %3Cpath d='M111z'/%3E %3C/svg%3E");
}
```
